# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf8d74d440cad10c9354386a63b8343a9319b99e7194628869c8355ad293983d75f65076d551a4bb96d1fb8e069a68f492460d98b6f3d81bddd9c2fa55700029

test:
  secret_key_base: e405effd05ade47a417c8fb503e23a229144b59cd5ac76f969d245174bbdeda100c99b4cf77a778547f9ace3b1e207590c42c137cf5f2bbeeae018698398fdce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
